title:            "Xavier Shay: Citizen"
description:      I write about things.
canonical: https://xaviershay.github.io/blog/
baseurl: /blog

enforce_ssl: xaviershay.github.io

# Owner/author information
owner:
  name:           Xavier Shay
  email:          contact@xaviershay.com
  twitter:        xshay
  github:         xaviershay
  location:       "San Franciso, USA"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Archive
    url: /articles/
  - title: About Me
    url: http://xaviershay.com
    external: true

archive_tags: ["politics", "law", "reviews", "other"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title.html

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
